In [5]:
# pd.DataFrame to make categorical table

import pandas as pd
import numpy as np
data=pd.DataFrame({
    'a':[1,2,3,4,5],
    'b':[-1,-3,-5,-7,-9],
    'c':[7,8,9,10,11]
})
data



a  b   c
0  1 -1   7
1  2 -3   8
2  3 -5   9
3  4 -7  10
4  5 -9  11

In [18]:
# pd.Index to make index table

data.columns
pd.Index(['a','b','c'],dtype='object')
data.values

array([[ 1, -1,  7],
       [ 2, -3,  8],
       [ 3, -5,  9],
       [ 4, -7, 10],
       [ 5, -9, 11]], dtype=int64)

In [6]:
#pd.DataFrame(data.values, columns=[]) another way to make categorical table

pd.DataFrame(data.values, columns=['a','b', 'c'])

a  b   c
0  1 -1   7
1  2 -3   8
2  3 -5   9
3  4 -7  10
4  5 -9  11

In [8]:
# data.copy(): for putting in another column later

df3 = data.copy()
df3['strings'] = ['a', 'b', 'v', 'd', 'e']
df3

a  b   c strings
0  1 -1   7       a
1  2 -3   8       b
2  3 -5   9       v
3  4 -7  10       d
4  5 -9  11       e

In [10]:
# .values to print output as arrays

df3.values

array([[1, -1, 7, 'a'],
       [2, -3, 8, 'b'],
       [3, -5, 9, 'v'],
       [4, -7, 10, 'd'],
       [5, -9, 11, 'e']], dtype=object)

In [2]:
import pandas as pd
data=pd.DataFrame({
    'a':[1,2,3,4,5],
    'b':[1,-3,5,7,9],
    'c':[7,8,9,10,11]
})
model_cols=['a','b']
data.loc[:, model_cols].values

array([[ 1,  1],
       [ 2, -3],
       [ 3,  5],
       [ 4,  7],
       [ 5,  9]], dtype=int64)

In [17]:

data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                  categories=['a', 'b'])
data

a  b   c category
0  1 -1   7        a
1  2 -3   8        b
2  3 -5   9        a
3  4 -7  10        a
4  5 -9  11        b

In [8]:
import pandas as pd
data=pd.DataFrame({
    'a':[1,2,3,4,5],
    'b':[-1,-3,-5,-7,-9],
    'c':[7,8,9,10,11]
})

data['category']=pd.Categorical(['a','b','a','a','b'],
                                categories=['a','b'])
data

dummies = pd.get_dummies(data.category, prefix='category')
data_with_dummies=data.drop('category',axis=1).join(dummies)
data_with_dummies

a  b   c  category_a  category_b
0  1 -1   7           1           0
1  2 -3   8           0           1
2  3 -5   9           1           0
3  4 -7  10           1           0
4  5 -9  11           0           1